### ISSUE TITLE
Credit?

### ISSUE THREAD

**Issue by ghost** [csf30816/svg-emoji#2]
I was wondering if I needed to give credit to you to use this on any of my websites. Nice job, by the way!

**Comment by csf30816** [comment]
Thanks. No need. But if you want to I am not holding you back :)

**Comment by ghost** [comment]
Alright! I added it on my GitHub pages site (thelukeguy.github.io) and used it a couple times, and I'll probably use it on my personal website soon. I did give credit to you on my GitHub Pages site. I really like this!

**Comment by csf30816** [comment]
Thanks so much! Currently working out some bugs. See [here](http://stackoverflow.com/questions/44090548/javascript-repeat-only-javascript-code?noredirect=1#comment75202948_44090548) You might be able to help.
