### ISSUE TITLE
Emojis not refreshing?

### ISSUE THREAD

**Issue by ghost** [csf30816/svg-emoji#4]
I'm trying to make a small addition to my GitHub Pages site. It's pretty silly, but if you look on thelukeguy.github.io and press the "Don't Click Me!" button, you can see a JavaScript alert that has :raging: three times and the button you just pressed has changed and has a :raging: as well. But all those 4 tags don't show the emojis.

**Comment by csf30816** [comment]
I know this issue. Trying to fix with setInterval but that crashed the JS. But the kind people at StackOverflow are helping me fix it.

**Comment by ghost** [comment]
Ah, ok. Good luck fixing it!

**Comment by csf30816** [comment]
Thank you.

**Comment by csf30816** [comment]
just use `<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>`
